/*
 * XenForo discussion.min.js
 * Copyright 2010-2018 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(c,g,f){c instanceof String&&(c=String(c));for(var k=c.length,a=0;a<k;a++){var b=c[a];if(g.call(f,b,a,c))return{i:a,v:b}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,g,f){c!=Array.prototype&&c!=Object.prototype&&(c[g]=f.value)};
$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(c,g,f,k){if(g){f=$jscomp.global;c=c.split(".");for(k=0;k<c.length-1;k++){var a=c[k];a in f||(f[a]={});f=f[a]}c=c[c.length-1];k=f[c];g=g(k);g!=k&&null!=g&&$jscomp.defineProperty(f,c,{configurable:!0,writable:!0,value:g})}};
$jscomp.polyfill("Array.prototype.find",function(c){return c?c:function(c,f){return $jscomp.findInternal(this,c,f).v}},"es6","es3");
!function(c,b,a,d){XenForo.QuickReply=function(f){if(c("#messageList").length==0){return console.error("Quick Reply not possible for %o, no #messageList found.",f)}var e=c('input[name="last_date"]',f);if(e.data("load-value")){e.val(Math.max(e.val(),e.data("load-value")))}var g=XenForo.MultiSubmitFix(f);this.scrollAndFocus=function(){c(a).scrollTop(f.offset().top);var h=XenForo.getEditorInForm(f);if(!h){return false}if(h.$editor){h.focus(true)}else{h.focus()}return this};f.data("QuickReply",this).bind({AutoValidationBeforeSubmit:function(h){if(c(h.clickedSubmitButton).is('input[name="more_options"]')){h.preventDefault();
h.returnValue=true}setTimeout(function(){c("#messageList").find(".messagesSinceReplyingNotice").remove()},250)},AutoValidationComplete:function(i){if(i.ajaxData._redirectTarget){b.location=i.ajaxData._redirectTarget}c('input[name="last_date"]',f).val(i.ajaxData.lastDate);if(g){g()}f.find("input:submit").blur();new XenForo.ExtLoader(i.ajaxData,function(){if("removeExisting" in i.ajaxData){c("#"+i.ajaxData.removeExisting).xfRemove(false,null,XenForo.speed.instant)}c(i.ajaxData.templateHtml).each(function(){if(this.tagName){c(this).xfInsert("appendTo",c("#messageList"))
}})});var j=c("#QuickReply").find("textarea");j.val("");var h=j.data("XenForo.BbCodeWysiwygEditor");if(h){h.resetEditor(null,true)}f.trigger("QuickReplyComplete");return false},BbCodeWysiwygEditorAutoSaveComplete:function(i){var h=c("#messageList"),j=h.find(".messagesSinceReplyingNotice");if(i.ajaxData.newPostCount&&i.ajaxData.templateHtml){if(j.length){j.remove();c(i.ajaxData.templateHtml).appendTo(h).show().xfActivate()}else{c(i.ajaxData.templateHtml).xfInsert("appendTo",h)}}else{j.remove()}}})};XenForo.QuickReplyTrigger=function(e){e.click(function(i){console.info("Quick Reply Trigger Click");
var h=null,j=null,g={},k=null,f=null;if(e.is(".MultiQuote")){h=c(e.data("form"))}else{h=c("#QuickReply");h.data("QuickReply").scrollAndFocus()}f=new c.Event("QuickReplyDataPrepare");f.$trigger=e;f.queryData=g;c(a).trigger(f);if(!j){j=XenForo.ajax(e.data("posturl")||e.attr("href"),g,function(l,n){if(XenForo.hasResponseError(l)){return false}delete (j);var m=XenForo.getEditorInForm(h);if(!m){return false}if(m.$editor){m.insertHtml(l.quoteHtml);console.info("QuoteHTML: %s",l.quoteHtml);if(m.$editor.data("xenForoElastic")){m.$editor.data("xenForoElastic")()
}}else{m.val(m.val()+l.quote)}if(e.is(".MultiQuote")){h.trigger("MultiQuoteComplete")}})}return false})};XenForo.InlineMessageEditor=function(e){new XenForo.MultiSubmitFix(e);e.bind({AutoValidationBeforeSubmit:function(f){if(c(f.clickedSubmitButton).is('input[name="more_options"]')){f.preventDefault();f.returnValue=true}},AutoValidationComplete:function(h){var f=e.closest("div.xenOverlay").data("overlay"),g=f.getTrigger().data("target");if(XenForo.hasTemplateHtml(h.ajaxData,"messagesTemplateHtml")||XenForo.hasTemplateHtml(h.ajaxData)){h.preventDefault();
f.close().getTrigger().data("XenForo.OverlayTrigger").deCache();XenForo.showMessages(h.ajaxData,f.getTrigger(),"instant")}else{console.warn("No template HTML!")}}})};XenForo.NewMessageLoader=function(e){var f=false;e.click(function(g){g.preventDefault();if(f){return}f=true;XenForo.ajax(e.data("href")||e.attr("href"),{},function(i){if(XenForo.hasResponseError(i)){return false}var j=c("#QuickReply"),h=c("#messageList");c('input[name="last_date"]',j).val(i.lastDate);new XenForo.ExtLoader(i,function(){h.find(".messagesSinceReplyingNotice").remove();
c(i.templateHtml).each(function(){if(this.tagName){c(this).xfInsert("appendTo",h)}})})}).always(function(){f=false})})};XenForo.MessageLoader=function(e){e.click(function(g){g.preventDefault();var f=[];c(e.data("messageselector")).each(function(h,j){f.push(j.id)});if(f.length){XenForo.ajax(e.attr("href"),{messageIds:f},function(h,i){XenForo.showMessages(h,e,"fadeDown")})}else{console.warn("No messages found to load.")}})};XenForo.showMessages=function(e,f,h){var g=function(i,j){switch(h){case"instant":h={show:"xfShow",hide:"xfHide",speed:0};
break;case"fadeIn":h={show:"xfFadeIn",hide:"xfFadeOut",speed:XenForo.speed.fast};break;case"fadeDown":default:h={show:"xfFadeDown",hide:"xfFadeUp",speed:XenForo.speed.normal}}c(i)[h.hide](h.speed/2,function(){c(j).xfInsert("replaceAll",i,h.show,h.speed)})};if(XenForo.hasResponseError(e)){return false}if(XenForo.hasTemplateHtml(e,"messagesTemplateHtml")){new XenForo.ExtLoader(e,function(){c.each(e.messagesTemplateHtml,g)})}else{if(XenForo.hasTemplateHtml(e)){new XenForo.ExtLoader(e,function(){g(f.data("messageselector"),e.templateHtml)
})}}};XenForo.PollVoteForm=function(e){var f=function(h){new XenForo.ExtLoader(h,function(){var i=e.closest(".PollContainer");e.xfFadeUp(XenForo.speed.normal,function(){e.empty().remove();var j=c(h.templateHtml);if(j.is(".PollContainer")){j=j.children()}else{if(j.find(".PollContainer").length){j=j.find(".PollContainer").children()}}j.xfInsert("appendTo",i);i.xfActivate()},XenForo.speed.normal,"swing")})};e.bind("AutoValidationComplete",function(h){h.preventDefault();if(XenForo.hasTemplateHtml(h.ajaxData)){f(h.ajaxData)}});e.on("click",".PollChangeVote",function(h){h.preventDefault();
XenForo.ajax(c(h.target).attr("href"),{},function(i){if(XenForo.hasTemplateHtml(i)){f(i)}},{method:"get"})});var g=e.data("max-votes")||0;if(g>1){e.on("click",".PollResponse",function(j){var h=e.find(".PollResponse"),i=h.filter(":not(:checked)");if(h.length-i.length>=g){i.prop("disabled",true)}else{i.prop("disabled",false)}})}};XenForo.MultiQuote=function(e){this.__construct(e)};XenForo.MultiQuote.prototype={__construct:function(f){this.$button=f.click(c.context(this,"prepareOverlay"));this.$form=f.closest("form");this.cookieName=f.data("mq-cookie")||"MultiQuote";
this.cookieValue=[];this.submitUrl=f.data("submiturl");this.$controls=new jQuery();this.getCookieValue();this.setButtonState();var e=this;this.$form.bind("MultiQuoteComplete",c.context(this,"reset"));this.$form.bind("MultiQuoteRemove MultiQuoteAdd",function(h,g){if(g&&g.messageId){e.toggleControl(g.messageId,h.type=="MultiQuoteAdd")}});c(a).bind("QuickReplyDataPrepare",c.context(this,"quickReplyDataPrepare"))},getCookieValue:function(){var e=c.getCookie(this.cookieName);this.cookieValue=(e==null?[]:e.split(","))},setButtonState:function(){this.getCookieValue();
if(this.cookieValue.length){this.$button.show()}else{this.$button.hide()}},addControl:function(e){e.click(c.context(this,"clickControl"));this.getCookieValue();this.setControlState(e,(c.inArray(e.data("messageid")+"",this.cookieValue)>=0),true);this.$controls=this.$controls.add(e)},setControls:function(){var e=this;e.getCookieValue();this.$controls.each(function(){e.setControlState(c(this),(c.inArray(c(this).data("messageid")+"",e.cookieValue)>=0))})},setControlState:function(g,f,i){var j,h=this.$button,e;if(f){j=h.data("remove")||"-";
e=true}else{j=h.data("add")||"+";e=false}if(!i||g.hasClass("active")!==e){g.toggleClass("active",f).find("span.symbol").text(j)}},clickControl:function(j){j.preventDefault();var h,k,g,f,i;h=c(j.target).closest("a.MultiQuoteControl");if(h.is(".QuoteSelected")){k=true;g=c("#QuoteSelected").data("quote-html");h.trigger("QuoteSelectedClicked")}else{k=!h.is(".active");g=null}f=h.data("messageid");this.toggleControl(f,k,g);if(i=this.$button.data(k?"add-message":"remove-message")){XenForo.alert(i,"",2000)}},toggleControl:function(k,j,f){this.getCookieValue();
var l=null;k+="";if(k.indexOf("-")>0){var h=k.split("-");k=h[0];l=h[1]}var g,e=c.inArray(k,this.cookieValue);g=this.$controls.filter(function(){return c(this).data("messageid")==k}).first();if(j){if(g.length){this.setControlState(g,true)}if(f!==null){this.storeSelectedQuote(k,f)}else{this.removeQuotesFromStorage(k)}if(e<0){this.cookieValue.push(k)}}else{this.removeQuotesFromStorage(k,l);if(!this.getStorageForId(k)){if(g.length){this.setControlState(g,false)}if(e>=0){this.cookieValue.splice(e,1)}}}if(this.cookieValue.length>0){c.setCookie(this.cookieName,this.cookieValue.join(","))
}else{c.deleteCookie(this.cookieName)}this.setButtonState()},storeSelectedQuote:function(h,e){var g=this.getStorageObject(),f=0;if(!g[h]||typeof g[h]!="object"){g[h]={}}c.each(g[h],function(i){f=i});f=parseInt(f,10)+1;g[h][f]=e;this.saveStorageObject(g)},removeQuotesFromStorage:function(h,e){var g=this.getStorageObject();h+="";if(!e&&h.indexOf("-")>0){var f=h.split("-");h=f[0];e=f[1]}if(e){delete g[h][e];if(c.isEmptyObject(g[h])){delete g[h]}}else{delete g[h]}this.saveStorageObject(g)},getStorageObject:function(){if(!b.localStorage){return{}
}var f=null;try{f=JSON.parse(localStorage.getItem(this.cookieName))}catch(g){}if(f===null||typeof f!=="object"){f={}}return f},getStorageForId:function(f){var e=this.getStorageObject();if(e[f]&&typeof e[f]=="object"&&!c.isEmptyObject(e[f])){return e[f]}return null},getStorageObjectFlat:function(){var e={};c.each(this.getStorageObject(),function(g,f){if(typeof f!="object"){return}c.each(f,function(i,h){e[g+"-"+i]=h})});return e},saveStorageObject:function(e){if(b.localStorage){localStorage.setItem(this.cookieName,JSON.stringify(e))
}},prepareOverlay:function(g){var f=this.getStorageObjectFlat();c.each(f,function(h,e){f[h]=XenForo.unparseBbCode(e)});XenForo.ajax(this.$button.data("href"),{quoteSelections:f},function(e,h){if(XenForo.hasTemplateHtml(e)){new XenForo.ExtLoader(e,function(i){i.noCache=true;XenForo.createOverlay(null,i.templateHtml,i).load()})}})},quickReplyDataPrepare:function(g){if(g.$trigger.is(".MultiQuote")){var f=this.getStorageObjectFlat();c.each(f,function(h,e){f[h]=XenForo.unparseBbCode(e)});g.queryData.quoteSelections=f;g.queryData.postIds=c(g.$trigger.data("inputs")).map(function(){return this.value
}).get()}},reset:function(){c.deleteCookie(this.cookieName);this.cookieValue=[];if(b.localStorage){localStorage.removeItem(this.cookieName)}this.setControls();this.setButtonState()}};XenForo.MultiQuoteControl=function(f){var e=f.data("mq-target")||"#MultiQuote",g=c(e).data("XenForo.MultiQuote");if(!g){return}g.addControl(f)};XenForo.MultiQuoteRemove=function(e){e.click(function(){var i=e.closest(".MultiQuoteItem"),h=i.find(".MultiQuoteId").val(),g=c(c("#MultiQuoteForm").data("form")),f=e.closest(".xenOverlay");if(h){g.trigger("MultiQuoteRemove",{messageId:h})
}i.remove();if(f.length&&!f.find(".MultiQuoteItem").length){f.overlay().close()}})};XenForo.Sortable=function(e){e.sortable({forcePlaceholderSize:true}).bind({sortupdate:function(f){},dragstart:function(f){console.log("drag start, %o",f.target)},dragend:function(f){console.log("drag end")}})};XenForo.SelectQuotable=function(e){this.__construct(e)};XenForo.SelectQuotable.prototype={__construct:function(i){if(!b.getSelection){return}if(!c("#QuickReply").length){return}this.$messageTextContainer=null;var f=this,e=false,h,g=function(){if(!h&&!f.processing){h=setTimeout(function(){h=null;
f._handleSelection()},100)}};i.on("mousedown",function(){e=true});i.on("mouseup",function(){e=false;g()});c(a).on("selectionchange",function(){if(!e){g()}});c(a).on("QuickReplyDataPrepare",function(j){var k=j.$trigger.closest("#QuoteSelected");if(k.length){j.queryData.quoteHtml=XenForo.unparseBbCode(k.data("quote-html"));j.$trigger.trigger("QuoteSelectedClicked")}})},buttonClicked:function(){var e=b.getSelection();if(!e.isCollapsed){e.collapse(e.getRangeAt(0).commonAncestorContainer,0);this.hideQuoteButton()}},_handleSelection:function(){this.processing=true;
var f=b.getSelection();if(this._isValidSelection(f)){this.showQuoteButton(f)}else{this.hideQuoteButton()}var e=this;setTimeout(function(){e.processing=false},0)},_isValidSelection:function(g){this.$messageTextContainer=null;if(g.isCollapsed||!g.rangeCount){return false}var e=g.getRangeAt(0);this._adjustRange(e);if(!c.trim(e.toString()).length){if(!e.cloneContents().querySelectorAll("img").length){return false}}var h=c(e.commonAncestorContainer).closest(".SelectQuoteContainer");if(!h.length){return false}var f=h.closest(".message");
if(!f.find("a.MultiQuoteControl, a.ReplyQuote").length){return false}if(c(e.startContainer).closest(".bbCodeQuote, .NoSelectToQuote").length||c(e.endContainer).closest(".bbCodeQuote, .NoSelectToQuote").length){return false}this.$messageTextContainer=h;return true},_adjustRange:function(e){var i=false,g=false;if(e.endOffset==0){var f=c(e.endContainer);if(e.endContainer.nodeType==3&&!e.endContainer.previousSibling){f=f.parent()}g=f.is(".quote, .attribution, .bbCodeQuote")}if(g){var j=c(e.endContainer).closest(".bbCodeQuote");if(j.length){e.setEndBefore(j[0]);
i=true}}if(i){var h=b.getSelection();h.removeAllRanges();h.addRange(e)}},showQuoteButton:function(f){var i=this.$messageTextContainer.closest("[id]").attr("id");if(this.$button===undefined||this.$button.data("id")!==i){this.hideQuoteButton();this.createButton();this.$button.data("id",i)}this.$button.data("quote-html",this.getSelectionHtml(f));var e=this.$button.width();var h=this.getButtonPositionMarker(f),g=this.$messageTextContainer?this.$messageTextContainer.offset().left:0;if(h.left-e<g){this.$button[XenForo.isRTL()?"addClass":"removeClass"]("flipped").css("left",h.left-16)
}else{this.$button[XenForo.isRTL()?"removeClass":"addClass"]("flipped").css("left",h.left-e-5)}this.$button.css({position:"absolute",top:h.top+6}).show()},getButtonPositionMarker:function(k){var n,j,h,m,e;n=c("<span />");n.text(c.browser.opera?"x":"\u200B");j=k.getRangeAt(0).cloneRange();e=j.getBoundingClientRect?j.getBoundingClientRect():null;j.collapse(false);j.insertNode(n[0]);var i,f=0;do{i=false;f++;if(n[0].parentNode&&n[0].parentNode.className=="messageTextEndMarker"){n.insertBefore(n[0].parentNode);i=true}if(n[0].previousSibling&&n[0].previousSibling.nodeType==3&&c.trim(n[0].previousSibling.textContent).length==0){n.insertBefore(n[0].previousSibling);
i=true}if(n[0].parentNode&&n[0].parentNode.tagName=="LI"&&!n[0].previousSibling){var l=n[0].parentNode;if(c(l).prev("li").length){n.appendTo(c(l).prev("li"));i=true}else{if(l.parentNode){n.insertBefore(l.parentNode);i=true}}}if(n[0].parentNode&&!n[0].previousSibling&&c.inArray(n[0].parentNode.tagName,["DIV","BLOCKQUOTE","PRE"])!=-1){n.insertBefore(n[0].parentNode);i=true}if(n[0].previousSibling&&c.inArray(n[0].previousSibling.tagName,["OL","UL"])!=-1){c(n[0].previousSibling).find("li:last").append(n);i=true}if(n[0].previousSibling&&c.inArray(n[0].previousSibling.tagName,["DIV","BLOCKQUOTE","PRE"])!=-1){n.appendTo(n[0].previousSibling);
i=true}if(n[0].previousSibling&&n[0].previousSibling.tagName=="BR"){n.insertBefore(n[0].previousSibling);i=true}}while(i&&f<5);h=n.offset();m=n.height();n.parentsUntil("body").each(function(){var q=c(this),p,o;switch(q.css("overflow-x")){case"hidden":case"scroll":case"auto":p=q.offset().left;o=p+q.outerWidth();if(h.left<p){h.left=p}if(o<h.left){h.left=o}}});var g=n.parent();n.remove();if(!c.browser.msie){g[0].normalize()}if(e&&!XenForo.isRTL()){if(h.left-e.left>32){h.left-=16}}h.top+=m;return h},createButton:function(){if(!this.$messageTextContainer.length){return false
}var g=this.$messageTextContainer.closest(".message");this.$button=c('<div id="QuoteSelected" class="xenTooltip"></div>').click(c.context(this,"hideQuoteButton")).append('<span class="arrow"></span>');var f=g.find("a.MultiQuoteControl").first().clone();if(f.length){f.addClass("QuoteSelected").attr("title","").on("QuoteSelectedClicked",c.context(this,"buttonClicked"));f.find("span.symbol").text(c(".MultiQuoteWatcher").data("add"));new XenForo.MultiQuoteControl(f);this.$button.append(f);this.$button.append(a.createTextNode(" | "))
}var i=g.find("a.ReplyQuote").clone();i.addClass("QuoteSelected").attr("title","").on("QuoteSelectedClicked",c.context(this,"buttonClicked"));new XenForo.QuickReplyTrigger(i);this.$button.append(i);c(a.body).append(this.$button);var e=this,h=c(b).width();c(b).on("resize.SelectQuotable",function(k){var j=c(b).width();if(j!=h){h=j;e._handleSelection()}});c(a).on("XFOverlay.SelectQuotable",function(j){e.hideQuoteButton();b.getSelection().collapseToEnd()})},hideQuoteButton:function(){if(this.$button!==undefined){this.$button.remove();
delete (this.$button)}c(b).off("resize.SelectQuotable");c(a).off("XFOverlay.SelectQuotable")},getSelectionHtml:function(h){var g=a.createElement("div"),f,e;for(f=0,e=h.rangeCount;f<e;f++){g.appendChild(h.getRangeAt(f).cloneContents())}return this.prepareSelectionHtml(g.innerHTML)},prepareSelectionHtml:function(e){return e}};XenForo.unparseBbCode=function(f){var e=c(a.createElement("div"));e.html(f);console.log(e.find(".bbCodeQuote").length);e.find(".NoSelectToQuote").each(function(){c(this).remove()});c.each(["B","I","U"],function(h,g){e.find(g).each(function(){c(this).replaceWith("["+g+"]"+c(this).html()+"[/"+g+"]")
})});e.find(".bbCodeQuote").each(function(){var g=c(this),h=g.find(".quote");if(h.length){g.replaceWith("<div>[QUOTE]"+h.html()+"[/QUOTE]</div>")}else{h.find(".quoteExpand").remove()}});e.find(".bbCodeCode, .bbCodeHtml, .bbCodePHP").each(function(){var i=c(this),h=c(this).find("div.type").first().text(),g="pre";if(h!==""){h=h.replace(/^(.+):$/,"$1")}if(i.is(".bbCodePHP")){g="code"}i.replaceWith(i.find(g).first().attr("data-type",h))});e.find('div[style*="text-align"]').each(function(){var g=c(this).css("text-align").toUpperCase();
c(this).replaceWith("["+g+"]"+c(this).html()+"[/"+g+"]")});e.find(".bbCodeSpoilerContainer").each(function(){var i,j,h,g;i=c(this).find(".bbCodeSpoilerButton");if(i.length){j=i.data("target");if(j){g=c(this).find(j).html();$spoilerTitle=c(this).find(".SpoilerTitle");if($spoilerTitle.length){h='="'+$spoilerTitle.text()+'"'}else{h=""}c(this).replaceWith("[SPOILER"+h+"]"+g+"[/SPOILER]")}}});console.info("HTML to be sent: %s",e.html());return e.html()};XenForo.register("#QuickReply","XenForo.QuickReply");XenForo.register("a.ReplyQuote, a.MultiQuote, a.QuoteSelected","XenForo.QuickReplyTrigger");
XenForo.register("form.InlineMessageEditor","XenForo.InlineMessageEditor");XenForo.register("a.MessageLoader","XenForo.MessageLoader");XenForo.register("a.NewMessageLoader","XenForo.NewMessageLoader");XenForo.register("form.PollVoteForm","XenForo.PollVoteForm");XenForo.register(".MultiQuoteWatcher","XenForo.MultiQuote");XenForo.register("a.MultiQuoteControl","XenForo.MultiQuoteControl");XenForo.register("a.MultiQuoteRemove","XenForo.MultiQuoteRemove");XenForo.register(".Sortable","XenForo.Sortable");XenForo.register(".SelectQuotable","XenForo.SelectQuotable")
}(jQuery,this,document);